### ISSUE TITLE
Does It work on 10.7 2ds?

### ISSUE THREAD

**Issue by lolbob181** [nedwill/soundhax#17] opened 2016-12-28 21:38 UTC
I have a europe 10.7 2ds will it work?

**Comment by Lordmau5** [comment] 2016-12-28 21:41
Right now we don't have the sound constants or stage2 payload constants.
Thus it is not possible *yet*.

**Comment by Irastris** [comment] 2016-12-28 21:47
This is not an issue, this is a question.

And to answer that question, no. European 2DS consoles do not currently work with soundhax.

**Comment by grifnelle** [comment] 2016-12-28 21:52
the 3ds version doesnt matter at all it willl work from 9.2-11.2. the issue is that the new ds and the old ds have slightly differnet codes and this code (the soundhax) only has the new 3ds code AS OF RIGHT NOW GIVE IT A DAY OR TWO PEOPLE

**Comment by lolbob181** [comment] 2016-12-28 22:30
Thanks for fast replys :)

**Comment by nedwill** [comment] 2016-12-29 00:54
O3DS should be working now, mind double checking? There's a download on the main page for you.

**Comment by RobTS** [comment] 2016-12-29 08:56
Confirmed working with 11.0.0.0-33E 2DS.

**Comment by lolbob181** [comment] 2016-12-29 10:06
Yesss

**Comment by lolbob181** [comment] 2016-12-29 10:24
Dosen't work on 10.7 EU 2DS only shows the green and crashes i uploaded starter.zip and this post5_e_24... into root with the .m4a :(

**Comment by Lordmau5** [comment] 2016-12-29 10:27
@lolbob181 you need to rename the `.bin` file to `otherapp.bin` :P

**Comment by lolbob181** [comment] 2016-12-29 10:35
:P no but i did and it works am retarted :(

**Comment by kade-robertson** [comment] 2016-12-29 13:36
Now that you have this working, you could close the issue so that those still having problems can have their posts seen better. :)

**Closed** 2016-12-29 14:46 UTC
