### ISSUE TITLE
Don´t work 11.0 2ds eu

### ISSUE THREAD

**Issue by peleonyt** [nedwill/soundhax#38] opened 2016-12-29 12:11 UTC
I tryed to use it, but I cant, it give a error (like return to home menu when u bypass with ctr-httpwn)

**Comment by SeyfWolf** [comment] 2016-12-29 12:46
Me neither.

**Comment by kade-robertson** [comment] 2016-12-29 13:29
I have found [these](https://www.reddit.com/r/3dshacks/comments/5kqpy6/soundhax_repo_made_public/dbqrj3v/) [two](https://www.reddit.com/r/3dshacks/comments/5kqpy6/soundhax_repo_made_public/dbqz86n/) comments on Reddit that suggest this does work on EUR O3DS and 2DS consoles. Can you describe the error further? More detail is always better.

**Comment by SeyfWolf** [comment] 2016-12-29 13:50
I have found a solution! 
First of all, my english isn't very good but i will try to explain it. 
The only thing that I have done is rename "theotherapp.bin" to "theotrherapp" and "boot.3dsx" to "boot". Finally, I haven't changed the name of "soundhax-eur-o3ds".
I hope it works for you. If so, spread the word! 
Sorry for my bad english again :D

**Comment by kade-robertson** [comment] 2016-12-29 13:57
That isn't necessarily a solution, you had simply named your files wrong. This means you had file extensions hidden, so your files were named `otherapp.bin.bin` and `boot.3dsx.3dsx`. You can turn on hidden file extensions in the Windows explorer to show this. :)

**Comment by SeyfWolf** [comment] 2016-12-29 14:02
Okay, sorry then. I just wanted to help. Thank you very much!

**Comment by kade-robertson** [comment] 2016-12-29 14:03
No worries! You definitely aren't the first and almost certainly won't be the last person to make the mistake. Plus hopefully people coming here for problems will search first and see your issue as a solution to their problem!

**Comment by KamikazePlatypus** [comment] 2016-12-29 14:17
Duplicate of #37.

**Closed** 2016-12-29 14:46 UTC
